# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go



  
name: Deploy to VPS
run-name: Deploy to VPS by @${{ github.actor }}
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        check-latest: true
    - name: Install SQLC
      run: | 
        go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest &&
        sqlc generate

    - name: Build
      run: GOOS=linux GOARCH=arm64 go build -v -o wutArm ./

    - name: Send
      run: scp ./wutArm ec2-user@3.144.91.239:~/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      

    
